# Generated by Django 3.1.4 on 2021-05-19 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200702_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 15, 17, 12, 650921, tzinfo=utc)),
        ),
    ]
