# Generated by Django 3.1.4 on 2021-05-20 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210520_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 18, 9, 33, 856556, tzinfo=utc)),
        ),
    ]
